DROP TABLE IF EXISTS TEMP.TEMP_DIM_ORG_MAPPING;
CREATE TABLE TEMP.TEMP_DIM_ORG_MAPPING
( 
  OC_ID STRING,
  OC_NAME STRING,
  RGN_ID STRING,
  RGN_NAME STRING,
  BASE_ID STRING,
  BASE_NAME STRING
  )
COMMENT '组织大区手工映射'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS TEXTFILE;