DROP TABLE IF EXISTS DW.DW_FIN_STORE_UNIT_PRICE;
CREATE TABLE IF NOT EXISTS DW.DW_FIN_STORE_UNIT_PRICE(
PERIOD_WID                     BIGINT                             COMMENT  '日期维ID',
MONTH_ID                       STRING                             COMMENT  '月份ID',
OC_ID                          STRING                             COMMENT  '运营中心',
RGN_ID                         STRING                             COMMENT  '大区ID',
RGN_NAME                       STRING                             COMMENT  '大区名称',
BASE_ID                        STRING                             COMMENT  '基地ID',
BASE_NAME                      STRING                             COMMENT  '基地名称',
BRAND_ID                       STRING                             COMMENT  '品牌ID',
BRAND_NAME                     STRING                             COMMENT  '品牌名称',
PROJ_ID                        STRING                             COMMENT  '项目ID',
PROJ_NAME                      STRING                             COMMENT  '项目名称',
WASH_CAR_FEE_INCOME_PRICE      decimal(32,8)                      COMMENT  '洗车费收入单价',
REVERSE_BIZ_INCOME_PRICE       decimal(32,8)                      COMMENT  '倒板业务收入单价',
WHARF_USE_FEE_INCOME_PRICE     decimal(32,8)                      COMMENT  '码头使用费收入单价',
PORT_OPER_FEE_INCOME_PRICE     decimal(32,8)                      COMMENT  '港口操作费收入单价',
PRE_SALE_MNT_FEE_INCOME_PRICE  decimal(32,8)                      COMMENT  '售前维护费收入单价',
REPAIR_MOVE_INCOME_PRICE       decimal(32,8)                      COMMENT  '返修挪车费收入单价',
SHORT_BARGE_FEE_INCOME_PRICE   decimal(32,8)                      COMMENT  '短驳费收入单价',
SERV_PROV_BUILD_INCOME_PRICE   decimal(32,8)                      COMMENT  '承运商维建费收入单价',
SERV_PROV_INSTORE_INCOME_PRICE decimal(32,8)                      COMMENT  '承运商中转入库服务费收入单价',
SERV_PROV_USESITE_INCOME_PRICE decimal(32,8)                      COMMENT  '承运商配装场地使用费收入单价',
STORE_MOVE_CAR_INCOME_PRICE    decimal(32,8)                      COMMENT  '库间挪车收入单价',
SERV_OUTSOURCE_INCOME_PRICE    decimal(32,8)                      COMMENT  '服务外包业务收入单价',
SMALL_REVERSE_INCOME_PRICE     decimal(32,8)                      COMMENT  '小倒运收入单价',
WASH_CAR_FEE_COST_PRICE        decimal(32,8)                      COMMENT  '洗车费成本单价',
REVERSE_TRANS_BIZ_COST_PRICE   decimal(32,8)                      COMMENT  '倒板业务成本单价',
WHARF_USE_FEE_COST_PRICE       decimal(32,8)                      COMMENT  '码头使用费成本单价',
PORT_OPER_FEE_COST_PRICE       decimal(32,8)                      COMMENT  '港口操作费成本单价',
PRE_SALE_MNT_FEE_COST_PRICE    decimal(32,8)                      COMMENT  '售前维护费成本单价',
REPAIR_MOVE_COST_PRICE         decimal(32,8)                      COMMENT  '返修挪车费成本单价',
SHORT_BARGE_FEE_COST_PRICE     decimal(32,8)                      COMMENT  '短驳费成本单价',
SERV_PROV_BUILD_COST_PRICE     decimal(32,8)                      COMMENT  '承运商维建费成本单价',
SERV_PROV_INSTORE_COST_PRICE   decimal(32,8)                      COMMENT  '承运商中转入库服务费成本单价',
SERV_PROV_USESITE_COST_PRICE   decimal(32,8)                      COMMENT  '承运商配装场地使用费成本单价',
STORE_MOVE_CAR_COST_PRICE      decimal(32,8)                      COMMENT  '库间挪车成本单价',
SERV_OUTSOURCE_COST_PRICE      decimal(32,8)                      COMMENT  '服务外包业务成本单价',
SMALL_REVERSE_COST_PRICE       decimal(32,8)                      COMMENT  '小倒运成本单价',
SOURCE_CODE                    STRING                             COMMENT  '源系统标识',
INTEGRATION_ID                 STRING                             COMMENT  '记录唯一标识',
AUX1_CHANGED_ON_DT             STRING                             COMMENT  '原系统记录创建时间',
W_INSERT_DT                    STRING                             COMMENT  '数据仓库插入时间',
W_UPDATE_DT                    STRING                             COMMENT  '数据仓库修改时间'
) 
COMMENT '仓储增值业务单价'
PARTITIONED BY(PART_DT STRING COMMENT  '分区时间')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036'
STORED AS PARQUET;