DROP TABLE IF EXISTS DW.DW_STR_STOCKDEPART;
CREATE TABLE IF NOT EXISTS DW.DW_STR_STOCKDEPART(
PERIOD_WID                    BIGINT                             COMMENT  '日期维ID(到达日)',
SEQNO                         BIGINT                             COMMENT  '序号',
PROCDATE                      STRING                             COMMENT  '业务日期',
PROCBILLNO                    STRING                             COMMENT  '业务单号',
PROCTYPE                      STRING                             COMMENT  '业务类型',
PLAN_TRANSPORTMODE_ID         STRING                             COMMENT  '计划运输方式',
TRANSPORTMODE_ID              STRING                             COMMENT  '运输方式',
GDLR_ID                       STRING                             COMMENT  '全局经销商代码',
DLR_ID                        STRING                             COMMENT  '经销商代码',
DLR_NAME                      STRING                             COMMENT  '经销商名称',
DEST_LOCATION_TYPE            STRING                             COMMENT  '目的地代码',
DEST_LOCATION_ID              STRING                             COMMENT  '目的地代码',
DEST_LOCATION_NAME            STRING                             COMMENT  '目的地名称',
VIN                           STRING                             COMMENT  'vin',
MODEL_ID                      STRING                             COMMENT  '车型ID',
BRAND_ID                      STRING                             COMMENT  '品牌ID',
OPT_CODE                      STRING                             COMMENT  '配置',
COL_CODE                      STRING                             COMMENT  '颜色',
SYMBOL                        STRING                             COMMENT  '标识',
DEPLOY                        STRING                             COMMENT  '调配标识',
STATE1                        STRING                             COMMENT  '当前状态',
STATE2                        STRING                             COMMENT  '上次状态',
GHIRERID                      STRING                             COMMENT  '全局货主代码',
HIRERID                       STRING                             COMMENT  '货物代码',
HIRERNAME                     STRING                             COMMENT  '货主名称',
FACTORY_ID                    STRING                             COMMENT  '工厂代码',
OC_ID                         STRING                             COMMENT  '运营中心ID',
OC_NAME                       STRING                             COMMENT  '运营中心',
RGN_ID                        STRING                             COMMENT  '大区ID',
RGN_NAME                      STRING                             COMMENT  '大区',
BASE_TYPE                     STRING                             COMMENT  '基地类型',
BASE_ID                       STRING                             COMMENT  '基地ID',
BASE_NAME                     STRING                             COMMENT  '基地',
STR_TYPE                      STRING                             COMMENT  '仓库类型',
STR_ID                        STRING                             COMMENT  '仓库ID',
STR_NAME                      STRING                             COMMENT  '仓库',
LOCATIONID1                   STRING                             COMMENT  '当前库位',
LOCATIONID2                   STRING                             COMMENT  '上次库位',
DRIVERID                      STRING                             COMMENT  '驾驶员代码',
DRIVERNAME                    STRING                             COMMENT  '驾驶员名称',
INSPECTORID                   STRING                             COMMENT  '检验员代码',
INSPECTORNAME                 STRING                             COMMENT  '检验员名称',
USERID                        STRING                             COMMENT  '操作员帐号',
USERNAME                      STRING                             COMMENT  '操作员名称',
PURCHASENO                    STRING                             COMMENT  '采购订单号',
SALESNO                       STRING                             COMMENT  '销售订单号',
SALESDATE                     STRING                             COMMENT  '销售订单日期',
VDRNO                         STRING                             COMMENT  '发运订单号',
ALLOTDATE                     STRING                             COMMENT  '发运订单日期',
MOVETOOGID                    STRING                             COMMENT  '移库目的组织代码',
MOVETOWHID                    STRING                             COMMENT  '移库目的库房代码',
REQRECEIVEDATE                STRING                             COMMENT  '要求收车日期',
SCHRECEIVEDATE                STRING                             COMMENT  '计划收车日期',
RECEIVEDATE                   STRING                             COMMENT  '收车日期',
INSTOCKDATE                   STRING                             COMMENT  '入库日期',
OUTSTOCKDATE                  STRING                             COMMENT  '出库时间',
REQSHIPPINGDATE               STRING                             COMMENT  '要求发运日期',
SCHSHIPPINGDATE               STRING                             COMMENT  '计划发运日期',
SHIPPINGDATE                  STRING                             COMMENT  '发运日期',
REQARRIVEDATE                 STRING                             COMMENT  '要求交付日期',
SCHARRIVEDATE                 STRING                             COMMENT  '计划交付日期',
ARRIVEDATE                    STRING                             COMMENT  '交付日期',
RFID                          STRING                             COMMENT  'rfid标签',
SHIPNO                        STRING,
SHIPNUMBER                    decimal(32,8) ,
PROJECTID                     STRING,
CARGOID                       STRING,
DEALERADD                     STRING,
SOURCE_CODE                   STRING                             COMMENT  '源系统标识',
INTEGRATION_ID                STRING                             COMMENT  '记录唯一标识',
AUX1_CHANGED_ON_DT            STRING                             COMMENT  '原系统记录创建时间',
W_INSERT_DT                   STRING                             COMMENT  '数据仓库插入时间',
W_UPDATE_DT                   STRING                             COMMENT  '数据仓库修改时间'
) 
COMMENT '仓库出入库记录'
PARTITIONED BY(PART_SC STRING COMMENT  '数据来源',PART_DT STRING COMMENT  '分区时间')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036'
STORED AS PARQUET;
