DROP TABLE IF EXISTS DW.DW_TP_ORDERMOVEMENT;
CREATE TABLE IF NOT EXISTS DW.DW_TP_ORDERMOVEMENT(
PERIOD_WID                    BIGINT                             COMMENT  '日期维ID(交付日/计划日)',
ORDER_MOVEMENT_GID            STRING                             COMMENT  '分段路由GID',
ORDER_RELEASE_GID             STRING                             COMMENT  'OTM单号',
BUDGET_SHIPMENT_GID           STRING                             COMMENT  '运输（财务）id',
SEQ_NO                        STRING                             COMMENT  '路由序列号',
YD_NO                         STRING                             COMMENT  '运单号',
OC_ID                         STRING                             COMMENT  '运营中心',
RGN_ID                        STRING                             COMMENT  '大区',
BASE_ID                       STRING                             COMMENT  '基地',
BASE_NAME                     STRING                             COMMENT  '基地名称',
PROJ_ID                       STRING                             COMMENT  '项目ID',
PROJ_NAME                     STRING                             COMMENT  '项目名称',
SOURCE_LOCATION_TYPE          STRING                             COMMENT  '始发地类型',
SOURCE_LOCATION_ID            STRING                             COMMENT  '始发地ID',
DEST_LOCATION_TYPE            STRING                             COMMENT  '目的地类型',
DEST_LOCATION_ID              STRING                             COMMENT  '目的地ID',
SOURCE_PRVN_ID                STRING                             COMMENT  '始发地省份',
SOURCE_CTY_ID                 STRING                             COMMENT  '始发地城市',
DEST_PRVN_ID                  STRING                             COMMENT  '目的地省份',
DEST_CTY_ID                   STRING                             COMMENT  '目的地城市',
DLR_ID                        STRING                             COMMENT  '主机厂经销店ID',
SUPPLIER_ID                   STRING                             COMMENT  '承运商',
VIN                           STRING                             COMMENT  'VIN码',
VIN_SIMPLE                    STRING                             COMMENT  'VIN简码',
BRAND_ID                      STRING                             COMMENT  '品牌ID',
PRODUCT_NAME                  STRING                             COMMENT  '主机厂车型代码 - 颜色 - 分类',
MODEL_ID                      STRING                             COMMENT  '车型ID',
MDLGRP_ID                     STRING                             COMMENT  '车型组',
ALL_TRANSPORTMODE             STRING                             COMMENT  '联运运输方式',
SEGMETN_TRANSPORTMODE         STRING                             COMMENT  '运输段运输方式',
TRANSPORTSTATUS               STRING                             COMMENT  '运输状态',
ORDER_STATUS                  STRING                             COMMENT  '订单状态',
ALLOT_STAUS                   STRING                             COMMENT  '分配状态(NEW/PROCESS/SUCCESS/FAIL)',
EARLY_PICKUP_DATE             STRING                             COMMENT  '计划日',
ICON4                         STRING                             COMMENT  '未使用',
ICON5                         STRING                             COMMENT  '未使用',
PERSPECTIVE                   STRING                             COMMENT  '指示这是买入还是卖出',
SERVPROV_GID                  STRING                             COMMENT  '虚拟承运商',
ORDER_RELEASE_NAME            STRING                             COMMENT  'FT板号 order release name',
DRIVER_PHONE                  STRING                             COMMENT  '驾驶员电话',
LIC_NO                        STRING                             COMMENT  '车牌号',
ALLOT_NO                      STRING                             COMMENT  '分拨单号',
TICKET_UNIT                   STRING                             COMMENT  '启票单位',
PLATE_NO                      STRING                             COMMENT  '分板序号',
DRIVER_VOYAGE_RAIL            STRING                             COMMENT  '驾驶员姓名/船名航次/铁路大组',
REST_REASON                   STRING                             COMMENT  '协力原因',
LSP                           STRING                             COMMENT  '实际承运商',
SSP                           STRING                             COMMENT  '份额承运商',
ORDER_COMMENT                 STRING                             COMMENT  '订单备注',
ON_PASSAGE_DAYS               decimal(32,8)                      COMMENT  '在途考核天数',
IS_STORAGE                    STRING                             COMMENT  '在途启票车辆是否已入库',
FACTORY_DAY                   STRING                             COMMENT  '出场日',
ARRANGE_DAY                   STRING                             COMMENT  '安排日(派车确认日)',
OUT_STORE_DAY                 STRING                             COMMENT  '出库日/中转出库日',
ALLOT_PLN_DAY                 STRING                             COMMENT  '调度分配计划日期',
DLVR_DAY                      STRING                             COMMENT  '中转入库日/交车日/到达日',
ARRIVAL_DAY                   STRING                             COMMENT  '到港日期',
SHIPMENT_DAY                  STRING                             COMMENT  '装船日期',
UNLOAD_DAY                    STRING                             COMMENT  '卸船日期',
LOAD_DAY                      STRING                             COMMENT  '装车日期',
LEAVE_BASE_DAY                STRING                             COMMENT  '离开基地和中转站日期',
MILEGE                        decimal(32,8)                      COMMENT  '里程(预算)',
AMOUNT_VALUE                  decimal(32,8)                      COMMENT  '总收入(预算)',
AMOUNT_COST                   decimal(32,8)                      COMMENT  '总成本(预算)',
AMOUNT_SEQ_VALUE              decimal(32,8)                      COMMENT  '段收入(预算)',
AMOUNT_SEQ_COST               decimal(32,8)                      COMMENT  '段成本(预算)',
SOURCE_CODE                   STRING                             COMMENT  '源系统标识',
INTEGRATION_ID                STRING                             COMMENT  '记录唯一标识',
AUX1_CHANGED_ON_DT            STRING                             COMMENT  '原系统记录创建时间',
W_INSERT_DT                   STRING                             COMMENT  '数据仓库插入时间',
W_UPDATE_DT                   STRING                             COMMENT  '数据仓库修改时间'
) 
COMMENT '路由'
PARTITIONED BY(PART_SC STRING COMMENT  '数据来源',PART_DT STRING COMMENT  '分区时间')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036'
STORED AS PARQUET;
