DROP TABLE IF EXISTS ODS_BLPT.T_HAND_PDI_CHECK_LV;
create table ODS_BLPT.T_HAND_PDI_CHECK_LV
(
  ID BIGINT,
  SEQ_ID STRING COMMENT '序号ID',
  RGN_NAME STRING COMMENT '大区名称',
  BASE_NAME STRING COMMENT '基地名称',
  BRAND_NAME STRING COMMENT '品牌名称',
  PRO_NAME STRING COMMENT '项目名称',
  CHECK_DAY STRING COMMENT '日期',
  WG STRING COMMENT '外观',
  GN STRING COMMENT '功能',
  QJ STRING COMMENT '缺件',
  DP STRING COMMENT '电瓶',
  QY STRING COMMENT '缺油',
  QT STRING COMMENT '其他',
  TOTAL_CNT STRING COMMENT 'PDI验收问题数合计',
  LAST_UPDATE_DATE STRING,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS PARQUET;


DROP TABLE IF EXISTS ODS_BLPT.STG_T_HAND_PDI_CHECK_LV;
create table ODS_BLPT.STG_T_HAND_PDI_CHECK_LV
(
  ID BIGINT,
  SEQ_ID STRING COMMENT '序号ID',
  RGN_NAME STRING COMMENT '大区名称',
  BASE_NAME STRING COMMENT '基地名称',
  BRAND_NAME STRING COMMENT '品牌名称',
  PRO_NAME STRING COMMENT '项目名称',
  CHECK_DAY STRING COMMENT '日期',
  WG STRING COMMENT '外观',
  GN STRING COMMENT '功能',
  QJ STRING COMMENT '缺件',
  DP STRING COMMENT '电瓶',
  QY STRING COMMENT '缺油',
  QT STRING COMMENT '其他',
  TOTAL_CNT STRING COMMENT 'PDI验收问题数合计',
  LAST_UPDATE_DATE STRING,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS TEXTFILE;

DROP TABLE IF EXISTS ODS_BLPT.HIS_T_HAND_PDI_CHECK_LV;
create table ODS_BLPT.HIS_T_HAND_PDI_CHECK_LV
(
  ID BIGINT,
  SEQ_ID STRING COMMENT '序号ID',
  RGN_NAME STRING COMMENT '大区名称',
  BASE_NAME STRING COMMENT '基地名称',
  BRAND_NAME STRING COMMENT '品牌名称',
  PRO_NAME STRING COMMENT '项目名称',
  CHECK_DAY STRING COMMENT '日期',
  WG STRING COMMENT '外观',
  GN STRING COMMENT '功能',
  QJ STRING COMMENT '缺件',
  DP STRING COMMENT '电瓶',
  QY STRING COMMENT '缺油',
  QT STRING COMMENT '其他',
  TOTAL_CNT STRING COMMENT 'PDI验收问题数合计',
  LAST_UPDATE_DATE STRING,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS PARQUET;