DROP TABLE IF EXISTS ODS_BLPT.T_HAND_REV_TICKET_PLAN;
create table ODS_BLPT.T_HAND_REV_TICKET_PLAN
(
  ID BIGINT,
  SEQ_ID STRING COMMENT '序号ID',
  MONTH_ID STRING COMMENT '月份ID',
  RGN_NAME STRING COMMENT '大区名称',
  BASE_NAME STRING COMMENT '基地名称',
  BRAND_NAME STRING COMMENT '品牌名称',
  PRO_NAME STRING COMMENT '项目名称',
  TP_MODE STRING COMMENT '发运方式',
  DES_CITY_NAME STRING COMMENT '目的城市',
  REV_PLAN STRING COMMENT '发运计划',
  LAST_UPDATE_DATE STRING,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS PARQUET;


DROP TABLE IF EXISTS ODS_BLPT.STG_T_HAND_REV_TICKET_PLAN;
create table ODS_BLPT.STG_T_HAND_REV_TICKET_PLAN
(
  ID BIGINT,
  SEQ_ID STRING COMMENT '序号ID',
  MONTH_ID STRING COMMENT '月份ID',
  RGN_NAME STRING COMMENT '大区名称',
  BASE_NAME STRING COMMENT '基地名称',
  BRAND_NAME STRING COMMENT '品牌名称',
  PRO_NAME STRING COMMENT '项目名称',
  TP_MODE STRING COMMENT '发运方式',
  DES_CITY_NAME STRING COMMENT '目的城市',
  REV_PLAN STRING COMMENT '发运计划',
  LAST_UPDATE_DATE STRING,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS TEXTFILE;

DROP TABLE IF EXISTS ODS_BLPT.HIS_T_HAND_REV_TICKET_PLAN;
create table ODS_BLPT.HIS_T_HAND_REV_TICKET_PLAN
(
  ID BIGINT,
  SEQ_ID STRING COMMENT '序号ID',
  MONTH_ID STRING COMMENT '月份ID',
  RGN_NAME STRING COMMENT '大区名称',
  BASE_NAME STRING COMMENT '基地名称',
  BRAND_NAME STRING COMMENT '品牌名称',
  PRO_NAME STRING COMMENT '项目名称',
  TP_MODE STRING COMMENT '发运方式',
  DES_CITY_NAME STRING COMMENT '目的城市',
  REV_PLAN STRING COMMENT '发运计划',
  LAST_UPDATE_DATE STRING,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS PARQUET;