DROP TABLE IF EXISTS ODS_BLPT.T_HAND_MARKET;
create table ODS_BLPT.T_HAND_MARKET
(
 ID BIGINT,
  MONTH_ID STRING COMMENT '月份',
  RGN_NAME STRING COMMENT '大区',
  BUS_TYPE STRING COMMENT '业务类别',
  BYL STRING COMMENT '保有量',
  KFBF_LV STRING COMMENT '客户拜访月度完成率',
  SJ_BF STRING COMMENT '月实际拜访量',
  JH_BF STRING COMMENT '月计划拜访量',
  TZXGPG STRING COMMENT '拓展效果评估',
  TZCB STRING COMMENT '拓展成本',
  TZCC STRING COMMENT '拓展产出',
  KF_LV STRING COMMENT '开发达成率',
  SJ_KF STRING COMMENT '月新客户实际开发数量',
  JH_KF STRING COMMENT '月新客户计划开发数量',
  SCXXFK STRING COMMENT '市场信息反馈量',
  JHPXCS STRING COMMENT '实际培训次数',
  LAST_UPDATE_DATE STRING,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS PARQUET;


DROP TABLE IF EXISTS ODS_BLPT.STG_T_HAND_MARKET;
create table ODS_BLPT.STG_T_HAND_MARKET
(
 ID BIGINT,
  MONTH_ID STRING COMMENT '月份',
  RGN_NAME STRING COMMENT '大区',
  BUS_TYPE STRING COMMENT '业务类别',
  BYL STRING COMMENT '保有量',
  KFBF_LV STRING COMMENT '客户拜访月度完成率',
  SJ_BF STRING COMMENT '月实际拜访量',
  JH_BF STRING COMMENT '月计划拜访量',
  TZXGPG STRING COMMENT '拓展效果评估',
  TZCB STRING COMMENT '拓展成本',
  TZCC STRING COMMENT '拓展产出',
  KF_LV STRING COMMENT '开发达成率',
  SJ_KF STRING COMMENT '月新客户实际开发数量',
  JH_KF STRING COMMENT '月新客户计划开发数量',
  SCXXFK STRING COMMENT '市场信息反馈量',
  JHPXCS STRING COMMENT '实际培训次数',
  LAST_UPDATE_DATE STRING,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS TEXTFILE;

DROP TABLE IF EXISTS ODS_BLPT.HIS_T_HAND_MARKET;
create table ODS_BLPT.HIS_T_HAND_MARKET
(
 ID BIGINT,
  MONTH_ID STRING COMMENT '月份',
  RGN_NAME STRING COMMENT '大区',
  BUS_TYPE STRING COMMENT '业务类别',
  BYL STRING COMMENT '保有量',
  KFBF_LV STRING COMMENT '客户拜访月度完成率',
  SJ_BF STRING COMMENT '月实际拜访量',
  JH_BF STRING COMMENT '月计划拜访量',
  TZXGPG STRING COMMENT '拓展效果评估',
  TZCB STRING COMMENT '拓展成本',
  TZCC STRING COMMENT '拓展产出',
  KF_LV STRING COMMENT '开发达成率',
  SJ_KF STRING COMMENT '月新客户实际开发数量',
  JH_KF STRING COMMENT '月新客户计划开发数量',
  SCXXFK STRING COMMENT '市场信息反馈量',
  JHPXCS STRING COMMENT '实际培训次数',
  LAST_UPDATE_DATE STRING,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS PARQUET;