DROP TABLE IF EXISTS ODS_BLPT.T_HAND_CUSTOMER_COMPLAINT;
create table ODS_BLPT.T_HAND_CUSTOMER_COMPLAINT
(
  ID BIGINT,
  MONTH_ID STRING COMMENT '月份ID',
  RGN_NAME STRING COMMENT '大区',
  BASE_NAME STRING COMMENT '基地',
  BRAND_NAME STRING COMMENT '品牌',
  TS_CNT STRING COMMENT '投诉数',
  TS_RT STRING COMMENT '投诉率',
  LAST_UPDATE_DATE STRING,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS PARQUET;


DROP TABLE IF EXISTS ODS_BLPT.STG_T_HAND_CUSTOMER_COMPLAINT;
create table ODS_BLPT.STG_T_HAND_CUSTOMER_COMPLAINT
(
  ID BIGINT,
  MONTH_ID STRING COMMENT '月份ID',
  RGN_NAME STRING COMMENT '大区',
  BASE_NAME STRING COMMENT '基地',
  BRAND_NAME STRING COMMENT '品牌',
  TS_CNT STRING COMMENT '投诉数',
  TS_RT STRING COMMENT '投诉率',
  LAST_UPDATE_DATE STRING,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS TEXTFILE;

DROP TABLE IF EXISTS ODS_BLPT.HIS_T_HAND_CUSTOMER_COMPLAINT;
create table ODS_BLPT.HIS_T_HAND_CUSTOMER_COMPLAINT
(
  ID BIGINT,
  MONTH_ID STRING COMMENT '月份ID',
  RGN_NAME STRING COMMENT '大区',
  BASE_NAME STRING COMMENT '基地',
  BRAND_NAME STRING COMMENT '品牌',
  TS_CNT STRING COMMENT '投诉数',
  TS_RT STRING COMMENT '投诉率',
  LAST_UPDATE_DATE STRING,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS PARQUET;