DROP TABLE IF EXISTS ODS_BLPT.T_HAND_WARNING_TARGET;
create table ODS_BLPT.T_HAND_WARNING_TARGET
(
  ID BIGINT,
  YEAR_ID STRING COMMENT '年份ID',
  INDEX_NAME STRING COMMENT '指标名称',
  RGN_NAME STRING COMMENT '大区',
  BASE_NAME STRING COMMENT '基地',
  BRAND_NAME STRING COMMENT '品牌',
  PRO_NAME STRING COMMENT '项目',
  JAN_PLAN_AMT STRING COMMENT '1月',
  FEB_PLAN_AMT STRING COMMENT '2月',
  MAR_PLAN_AMT STRING COMMENT '3月',
  APR_PLAN_AMT STRING COMMENT '4月',
  MAY_PLAN_AMT STRING COMMENT '5月',
  JUNE_PLAN_AMT STRING COMMENT '6月',
  JULY_PLAN_AMT STRING COMMENT '7月',
  AUG_PLAN_AMT STRING COMMENT '8月',
  SEPT_PLAN_AMT STRING COMMENT '9月',
  OCT_PLAN_AMT STRING COMMENT '10月',
  NOV_PLAN_AMT STRING COMMENT '11月',
  DEC_PLAN_AMT STRING COMMENT '12月',
  LAST_UPDATE_DATE STRING,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS PARQUET;


DROP TABLE IF EXISTS ODS_BLPT.STG_T_HAND_WARNING_TARGET;
create table ODS_BLPT.STG_T_HAND_WARNING_TARGET
(
  ID BIGINT,
  YEAR_ID STRING COMMENT '年份ID',
  INDEX_NAME STRING COMMENT '指标名称',
  RGN_NAME STRING COMMENT '大区',
  BASE_NAME STRING COMMENT '基地',
  BRAND_NAME STRING COMMENT '品牌',
  PRO_NAME STRING COMMENT '项目',
  JAN_PLAN_AMT STRING COMMENT '1月',
  FEB_PLAN_AMT STRING COMMENT '2月',
  MAR_PLAN_AMT STRING COMMENT '3月',
  APR_PLAN_AMT STRING COMMENT '4月',
  MAY_PLAN_AMT STRING COMMENT '5月',
  JUNE_PLAN_AMT STRING COMMENT '6月',
  JULY_PLAN_AMT STRING COMMENT '7月',
  AUG_PLAN_AMT STRING COMMENT '8月',
  SEPT_PLAN_AMT STRING COMMENT '9月',
  OCT_PLAN_AMT STRING COMMENT '10月',
  NOV_PLAN_AMT STRING COMMENT '11月',
  DEC_PLAN_AMT STRING COMMENT '12月',
  LAST_UPDATE_DATE STRING,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS TEXTFILE;

DROP TABLE IF EXISTS ODS_BLPT.HIS_T_HAND_WARNING_TARGET;
create table ODS_BLPT.HIS_T_HAND_WARNING_TARGET
(
  ID BIGINT,
  YEAR_ID STRING COMMENT '年份ID',
  INDEX_NAME STRING COMMENT '指标名称',
  RGN_NAME STRING COMMENT '大区',
  BASE_NAME STRING COMMENT '基地',
  BRAND_NAME STRING COMMENT '品牌',
  PRO_NAME STRING COMMENT '项目',
  JAN_PLAN_AMT STRING COMMENT '1月',
  FEB_PLAN_AMT STRING COMMENT '2月',
  MAR_PLAN_AMT STRING COMMENT '3月',
  APR_PLAN_AMT STRING COMMENT '4月',
  MAY_PLAN_AMT STRING COMMENT '5月',
  JUNE_PLAN_AMT STRING COMMENT '6月',
  JULY_PLAN_AMT STRING COMMENT '7月',
  AUG_PLAN_AMT STRING COMMENT '8月',
  SEPT_PLAN_AMT STRING COMMENT '9月',
  OCT_PLAN_AMT STRING COMMENT '10月',
  NOV_PLAN_AMT STRING COMMENT '11月',
  DEC_PLAN_AMT STRING COMMENT '12月',
  LAST_UPDATE_DATE STRING,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS PARQUET;