DROP TABLE IF EXISTS ODS_BLPT.T_HAND_YEAR_END_NUMBER_EMPLOYEES;
create table ODS_BLPT.T_HAND_YEAR_END_NUMBER_EMPLOYEES
(
  ID BIGINT ,
  SEQ_ID STRING  COMMENT '序号ID',
  YEAR_ID STRING  COMMENT '年份ID',
  MONTH_ID STRING  COMMENT '月份ID',
  RGN_NAME STRING  COMMENT '大区名称',
  PROJ_NAME STRING  COMMENT '项目名称',
  PEOPLE_PLAN_NUM STRING  COMMENT '人数计划',
  EMPLOYEES STRING  COMMENT '从业人数',
  EMP_ID STRING  COMMENT '管理序列',
  PROFESSIONAL_ID STRING  COMMENT '专业序列',
  OPERATE_ID STRING  COMMENT '操作序列',
  LAST_UPDATE_DATE STRING ,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING ,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS PARQUET;


DROP TABLE IF EXISTS ODS_BLPT.STG_T_HAND_YEAR_END_NUMBER_EMPLOYEES;
create table ODS_BLPT.STG_T_HAND_YEAR_END_NUMBER_EMPLOYEES
(
  ID BIGINT ,
  SEQ_ID STRING  COMMENT '序号ID',
  YEAR_ID STRING  COMMENT '年份ID',
  MONTH_ID STRING  COMMENT '月份ID',
  RGN_NAME STRING  COMMENT '大区名称',
  PROJ_NAME STRING  COMMENT '项目名称',
  PEOPLE_PLAN_NUM STRING  COMMENT '人数计划',
  EMPLOYEES STRING  COMMENT '从业人数',
  EMP_ID STRING  COMMENT '管理序列',
  PROFESSIONAL_ID STRING  COMMENT '专业序列',
  OPERATE_ID STRING  COMMENT '操作序列',
  LAST_UPDATE_DATE STRING ,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING ,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS TEXTFILE;

DROP TABLE IF EXISTS ODS_BLPT.HIS_T_HAND_YEAR_END_NUMBER_EMPLOYEES;
create table ODS_BLPT.HIS_T_HAND_YEAR_END_NUMBER_EMPLOYEES
(
  ID BIGINT ,
  SEQ_ID STRING  COMMENT '序号ID',
  YEAR_ID STRING  COMMENT '年份ID',
  MONTH_ID STRING  COMMENT '月份ID',
  RGN_NAME STRING  COMMENT '大区名称',
  PROJ_NAME STRING  COMMENT '项目名称',
  PEOPLE_PLAN_NUM STRING  COMMENT '人数计划',
  EMPLOYEES STRING  COMMENT '从业人数',
  EMP_ID STRING  COMMENT '管理序列',
  PROFESSIONAL_ID STRING  COMMENT '专业序列',
  OPERATE_ID STRING  COMMENT '操作序列',
  LAST_UPDATE_DATE STRING ,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING ,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS PARQUET;