DROP TABLE IF EXISTS ODS_BLPT.T_HAND_MARKET_LV;
create table ODS_BLPT.T_HAND_MARKET_LV
(
  ID BIGINT,
  MONTH_ID STRING COMMENT '月份',
  BRAND_NAME STRING COMMENT '品牌',
  YQYHTXL STRING COMMENT '已签约合同某产品销量',
  HTQYSY STRING COMMENT '合同签约的产品使用总数（季度）',
  LAST_UPDATE_DATE STRING,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS PARQUET;


DROP TABLE IF EXISTS ODS_BLPT.STG_T_HAND_MARKET_LV;
create table ODS_BLPT.STG_T_HAND_MARKET_LV
(
  ID BIGINT,
  MONTH_ID STRING COMMENT '月份',
  BRAND_NAME STRING COMMENT '品牌',
  YQYHTXL STRING COMMENT '已签约合同某产品销量',
  HTQYSY STRING COMMENT '合同签约的产品使用总数（季度）',
  LAST_UPDATE_DATE STRING,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS TEXTFILE;

DROP TABLE IF EXISTS ODS_BLPT.HIS_T_HAND_MARKET_LV;
create table ODS_BLPT.HIS_T_HAND_MARKET_LV
(
  ID BIGINT,
  MONTH_ID STRING COMMENT '月份',
  BRAND_NAME STRING COMMENT '品牌',
  YQYHTXL STRING COMMENT '已签约合同某产品销量',
  HTQYSY STRING COMMENT '合同签约的产品使用总数（季度）',
  LAST_UPDATE_DATE STRING,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS PARQUET;
