DROP TABLE IF EXISTS ODS_BLPT.T_HAND_ORG_COST;
create table ODS_BLPT.T_HAND_ORG_COST
(
  ID BIGINT,
  MONTH_ID STRING  COMMENT '月份ID',
  ORG_NAME STRING  COMMENT '大区/博宇',
  TOTAL_COST STRING  COMMENT '累计降本指标',
  COST_REAL STRING  COMMENT '实际降本',
  COMMENTS STRING  COMMENT '备注',
  LAST_UPDATE_DATE STRING ,
  LAST_UPDATED_BY STRING ,
  CREATION_DATE STRING ,
  CREATED_BY STRING 
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS PARQUET;


DROP TABLE IF EXISTS ODS_BLPT.STG_T_HAND_ORG_COST;
create table ODS_BLPT.STG_T_HAND_ORG_COST
(
  ID BIGINT,
  MONTH_ID STRING  COMMENT '月份ID',
  ORG_NAME STRING  COMMENT '大区/博宇',
  TOTAL_COST STRING  COMMENT '累计降本指标',
  COST_REAL STRING  COMMENT '实际降本',
  COMMENTS STRING  COMMENT '备注',
  LAST_UPDATE_DATE STRING ,
  LAST_UPDATED_BY STRING ,
  CREATION_DATE STRING ,
  CREATED_BY STRING 
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS TEXTFILE;

DROP TABLE IF EXISTS ODS_BLPT.HIS_T_HAND_ORG_COST;
create table ODS_BLPT.HIS_T_HAND_ORG_COST
(
  ID BIGINT,
  MONTH_ID STRING  COMMENT '月份ID',
  ORG_NAME STRING  COMMENT '大区/博宇',
  TOTAL_COST STRING  COMMENT '累计降本指标',
  COST_REAL STRING  COMMENT '实际降本',
  COMMENTS STRING  COMMENT '备注',
  LAST_UPDATE_DATE STRING ,
  LAST_UPDATED_BY STRING ,
  CREATION_DATE STRING ,
  CREATED_BY STRING 
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS PARQUET;
