DROP TABLE IF EXISTS ODS_BLPT.T_HAND_DLR_MYD;
create table ODS_BLPT.T_HAND_DLR_MYD
(
  ID BIGINT,
  BRAND_NAME STRING COMMENT '品牌',
  DLR_ID STRING COMMENT '经销商代码',
  DLR_NAME STRING COMMENT '经销商',
  PRVN_NAME STRING COMMENT '省份',
  HFR STRING COMMENT '回访人',
  HFFS STRING COMMENT '回访方式',
  SFR STRING COMMENT '受访人及联系电话(名字+电话)',
  SFRZW STRING COMMENT '受访人职务',
  PF STRING COMMENT '对物流服务的总体评分',
  ZTCX STRING COMMENT '在途查询',
  JCZL STRING COMMENT '交车质量',
  JCRYFW STRING COMMENT '交车人员的服务态度',
  TZPF STRING COMMENT '对商品车到达前通知执行情况评分',
  KFPF STRING COMMENT '对客服人员的服务态度与服务质量评分',
  RKSJ STRING COMMENT '经销商DMS入库时间',
  ZSCL STRING COMMENT '质损处理',
  JXSYJ STRING COMMENT '经销商意见',
  LAST_UPDATE_DATE STRING,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS PARQUET;


DROP TABLE IF EXISTS ODS_BLPT.STG_T_HAND_DLR_MYD;
create table ODS_BLPT.STG_T_HAND_DLR_MYD
(
  ID BIGINT,
  BRAND_NAME STRING COMMENT '品牌',
  DLR_ID STRING COMMENT '经销商代码',
  DLR_NAME STRING COMMENT '经销商',
  PRVN_NAME STRING COMMENT '省份',
  HFR STRING COMMENT '回访人',
  HFFS STRING COMMENT '回访方式',
  SFR STRING COMMENT '受访人及联系电话(名字+电话)',
  SFRZW STRING COMMENT '受访人职务',
  PF STRING COMMENT '对物流服务的总体评分',
  ZTCX STRING COMMENT '在途查询',
  JCZL STRING COMMENT '交车质量',
  JCRYFW STRING COMMENT '交车人员的服务态度',
  TZPF STRING COMMENT '对商品车到达前通知执行情况评分',
  KFPF STRING COMMENT '对客服人员的服务态度与服务质量评分',
  RKSJ STRING COMMENT '经销商DMS入库时间',
  ZSCL STRING COMMENT '质损处理',
  JXSYJ STRING COMMENT '经销商意见',
  LAST_UPDATE_DATE STRING,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS TEXTFILE;

DROP TABLE IF EXISTS ODS_BLPT.HIS_T_HAND_DLR_MYD;
create table ODS_BLPT.HIS_T_HAND_DLR_MYD
(
  ID BIGINT,
  BRAND_NAME STRING COMMENT '品牌',
  DLR_ID STRING COMMENT '经销商代码',
  DLR_NAME STRING COMMENT '经销商',
  PRVN_NAME STRING COMMENT '省份',
  HFR STRING COMMENT '回访人',
  HFFS STRING COMMENT '回访方式',
  SFR STRING COMMENT '受访人及联系电话(名字+电话)',
  SFRZW STRING COMMENT '受访人职务',
  PF STRING COMMENT '对物流服务的总体评分',
  ZTCX STRING COMMENT '在途查询',
  JCZL STRING COMMENT '交车质量',
  JCRYFW STRING COMMENT '交车人员的服务态度',
  TZPF STRING COMMENT '对商品车到达前通知执行情况评分',
  KFPF STRING COMMENT '对客服人员的服务态度与服务质量评分',
  RKSJ STRING COMMENT '经销商DMS入库时间',
  ZSCL STRING COMMENT '质损处理',
  JXSYJ STRING COMMENT '经销商意见',
  LAST_UPDATE_DATE STRING,
  LAST_UPDATED_BY STRING,
  CREATION_DATE STRING,
  CREATED_BY STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036' STORED AS PARQUET;