DROP TABLE IF EXISTS DIM.DIM_PERIOD_D;
CREATE TABLE IF NOT EXISTS DIM.DIM_PERIOD_D(
PERIOD_WID                    BIGINT                             COMMENT  '期间ID',
PERIOD_CODE                   STRING                             COMMENT  '期间编码',
PERIOD_DATE                   STRING                             COMMENT  '日期',
PERIOD_TYPE                   STRING                             COMMENT  '期间类型(D/M/Y/Q/H/W)',
DAY_NAME                      STRING                             COMMENT  '日名称',
WEEK_NAME                     STRING                             COMMENT  '周名称',
MONTH_NAME                    STRING                             COMMENT  '月名称',
QUARTER_NAME                  STRING                             COMMENT  '季度名称',
HALF_YEAR_NAME                STRING                             COMMENT  '半年名称',
YEAR_NAME                     STRING                             COMMENT  '年名称',
DAY_NBR_IN_WEEK               BIGINT                             COMMENT  '周内第几天',
DAY_NBR_IN_MONTH              BIGINT                             COMMENT  '月内第几天',
DAY_NBR_IN_YEAR               BIGINT                             COMMENT  '年内第几天',
WEEK_NBR_IN_MONTH             BIGINT                             COMMENT  '月内第几周',
WEEK_NBR_IN_YEAR              BIGINT                             COMMENT  '年内第几周',
MONTH_NBR_IN_YEAR             BIGINT                             COMMENT  '年内第几月',
QTR_NBR_IN_YEAR               BIGINT                             COMMENT  '年内第几季度',
HALF_NBR_IN_YEAR              BIGINT                             COMMENT  '年内第几半年',
FIRST_WEEK_IN_MONTH_FLAG      STRING                             COMMENT  '月第一周标记',
LAST_WEEK_IN_MONTH_FLAG       STRING                             COMMENT  '月最后一周标记',
FIRST_MONTH_IN_YEAR_FLAG      STRING                             COMMENT  '年第一月标记',
LAST_MONTH_IN_YEAR_FLAG       STRING                             COMMENT  '年最后一月标记',
PERIOD_STATS                  STRING                             COMMENT  '期间状态',
PERIOD_START_DT               STRING                             COMMENT  '期间开始日期',
PERIOD_START_DT_WID           BIGINT                             COMMENT  '期间开始WID',
PERIOD_END_DT                 STRING                             COMMENT  '期间结束日期',
PERIOD_END_DT_WID             BIGINT                             COMMENT  '期间结束WID',
CREATED_ON_DT                 STRING                             COMMENT  '原系统记录创建时间',
CHANGED_ON_DT                 STRING                             COMMENT  '原系统记录修改时间',
YEAR                          STRING                             COMMENT  '年',
MONTH                         STRING                             COMMENT  '月',
DAY                           STRING                             COMMENT  '日',
MONTH_START_DT_WID            BIGINT                             COMMENT  '月第一天',
MONTH_END_DT_WID              BIGINT                             COMMENT  '月最后一天',
AGO_PERIOD_WID                BIGINT                             COMMENT  '去年同期WID',
AGO_MONTH_START_DT_WID        BIGINT                             COMMENT  '去年同期月第一天',
AGO_MONTH_END_DT_WID          BIGINT                             COMMENT  '去年同期月最后一天',
AGO11_MONTH_START_DT_WID      BIGINT                             COMMENT  '去年同期下月第一天',
AGO11_MONTH_END_DT_WID        BIGINT                             COMMENT  '去年同期下月最后一天',
YEAR_START_DT_WID             BIGINT                             COMMENT  '年第一天',
YEAR_END_DT_WID               BIGINT                             COMMENT  '年最后一天',
AGO_YEAR_START_DT_WID         BIGINT                             COMMENT  '去年同期年第一天',
AGO_YEAR_END_DT_WID           BIGINT                             COMMENT  '全年同期年最后一天',
YEARMONTH                     BIGINT                             COMMENT  '年月',
AGO_YEARMONTH                 BIGINT                             COMMENT  '去年同期年月',
AGO11_YEARMONTH               BIGINT                             COMMENT  '去年同期下月',
LAST_MONTH_START_DT_WID       BIGINT                             COMMENT  '上月第一天',
LAST_MONTH_END_DT_WID         BIGINT                             COMMENT  '上月最后一天',
PRE_45_DAY_WID                BIGINT                             COMMENT  '往前第45天',
WEEK_NBR_IN_MONTH_IW          BIGINT                             COMMENT  '当月第几周',
WEEK_NBR_IN_YEAR_IW           BIGINT                             COMMENT  '当年第几周',
YEAR_IW                       BIGINT,
HOLIDAY_NAME                  STRING,
HOLIDAY_FLAG                  BIGINT,
FIN_START_DT_IN_MONTH         BIGINT                             COMMENT  '财务核算月份开始日期',
FIN_END_DT_IN_MONTH           BIGINT                             COMMENT  '财务核算月份结束日期',
FIN_IN_MONTH                  BIGINT                             COMMENT  '财务核算月份'
) 
COMMENT '期间维(项目)'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036'
STORED AS PARQUET;

DROP TABLE IF EXISTS DIM.HIS_DIM_PERIOD_D;
CREATE TABLE IF NOT EXISTS DIM.HIS_DIM_PERIOD_D(
PERIOD_WID                    BIGINT                             COMMENT  '期间ID',
PERIOD_CODE                   STRING                             COMMENT  '期间编码',
PERIOD_DATE                   STRING                             COMMENT  '日期',
PERIOD_TYPE                   STRING                             COMMENT  '期间类型(D/M/Y/Q/H/W)',
DAY_NAME                      STRING                             COMMENT  '日名称',
WEEK_NAME                     STRING                             COMMENT  '周名称',
MONTH_NAME                    STRING                             COMMENT  '月名称',
QUARTER_NAME                  STRING                             COMMENT  '季度名称',
HALF_YEAR_NAME                STRING                             COMMENT  '半年名称',
YEAR_NAME                     STRING                             COMMENT  '年名称',
DAY_NBR_IN_WEEK               BIGINT                             COMMENT  '周内第几天',
DAY_NBR_IN_MONTH              BIGINT                             COMMENT  '月内第几天',
DAY_NBR_IN_YEAR               BIGINT                             COMMENT  '年内第几天',
WEEK_NBR_IN_MONTH             BIGINT                             COMMENT  '月内第几周',
WEEK_NBR_IN_YEAR              BIGINT                             COMMENT  '年内第几周',
MONTH_NBR_IN_YEAR             BIGINT                             COMMENT  '年内第几月',
QTR_NBR_IN_YEAR               BIGINT                             COMMENT  '年内第几季度',
HALF_NBR_IN_YEAR              BIGINT                             COMMENT  '年内第几半年',
FIRST_WEEK_IN_MONTH_FLAG      STRING                             COMMENT  '月第一周标记',
LAST_WEEK_IN_MONTH_FLAG       STRING                             COMMENT  '月最后一周标记',
FIRST_MONTH_IN_YEAR_FLAG      STRING                             COMMENT  '年第一月标记',
LAST_MONTH_IN_YEAR_FLAG       STRING                             COMMENT  '年最后一月标记',
PERIOD_STATS                  STRING                             COMMENT  '期间状态',
PERIOD_START_DT               STRING                             COMMENT  '期间开始日期',
PERIOD_START_DT_WID           BIGINT                             COMMENT  '期间开始WID',
PERIOD_END_DT                 STRING                             COMMENT  '期间结束日期',
PERIOD_END_DT_WID             BIGINT                             COMMENT  '期间结束WID',
CREATED_ON_DT                 STRING                             COMMENT  '原系统记录创建时间',
CHANGED_ON_DT                 STRING                             COMMENT  '原系统记录修改时间',
YEAR                          STRING                             COMMENT  '年',
MONTH                         STRING                             COMMENT  '月',
DAY                           STRING                             COMMENT  '日',
MONTH_START_DT_WID            BIGINT                             COMMENT  '月第一天',
MONTH_END_DT_WID              BIGINT                             COMMENT  '月最后一天',
AGO_PERIOD_WID                BIGINT                             COMMENT  '去年同期WID',
AGO_MONTH_START_DT_WID        BIGINT                             COMMENT  '去年同期月第一天',
AGO_MONTH_END_DT_WID          BIGINT                             COMMENT  '去年同期月最后一天',
AGO11_MONTH_START_DT_WID      BIGINT                             COMMENT  '去年同期下月第一天',
AGO11_MONTH_END_DT_WID        BIGINT                             COMMENT  '去年同期下月最后一天',
YEAR_START_DT_WID             BIGINT                             COMMENT  '年第一天',
YEAR_END_DT_WID               BIGINT                             COMMENT  '年最后一天',
AGO_YEAR_START_DT_WID         BIGINT                             COMMENT  '去年同期年第一天',
AGO_YEAR_END_DT_WID           BIGINT                             COMMENT  '全年同期年最后一天',
YEARMONTH                     BIGINT                             COMMENT  '年月',
AGO_YEARMONTH                 BIGINT                             COMMENT  '去年同期年月',
AGO11_YEARMONTH               BIGINT                             COMMENT  '去年同期下月',
LAST_MONTH_START_DT_WID       BIGINT                             COMMENT  '上月第一天',
LAST_MONTH_END_DT_WID         BIGINT                             COMMENT  '上月最后一天',
PRE_45_DAY_WID                BIGINT                             COMMENT  '往前第45天',
WEEK_NBR_IN_MONTH_IW          BIGINT                             COMMENT  '当月第几周',
WEEK_NBR_IN_YEAR_IW           BIGINT                             COMMENT  '当年第几周',
YEAR_IW                       BIGINT,
HOLIDAY_NAME                  STRING,
HOLIDAY_FLAG                  BIGINT,
FIN_START_DT_IN_MONTH         BIGINT                             COMMENT  '财务核算月份开始日期',
FIN_END_DT_IN_MONTH           BIGINT                             COMMENT  '财务核算月份结束日期',
FIN_IN_MONTH                  BIGINT                             COMMENT  '财务核算月份'
) 
COMMENT '期间维(项目)'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036'
STORED AS PARQUET;