DROP TABLE IF EXISTS DIM.DIM_PROJ_STR_R;
CREATE TABLE IF NOT EXISTS DIM.DIM_PROJ_STR_R(
PROJ_ID            STRING  COMMENT  '项目ID',
PROJ_NAME          STRING  COMMENT  '项目名称',
BASE_ID            STRING  COMMENT  '基地ID',
BASE_NAME          STRING  COMMENT  '基地名称',
BRAND_ID           STRING  COMMENT  '品牌ID',
BRAND_NAME         STRING  COMMENT  '品牌名称',
STR_ID             STRING  COMMENT  '仓库ID',
STR_NAME           STRING  COMMENT  '仓库名称',
SOURCE_CODE        STRING  COMMENT  '来源',
W_INSERT_DT        STRING  COMMENT  '数据仓库记录插入时间 ',
W_UPDATE_DT        STRING  COMMENT  '数据仓库记录更新时间 ',
START_DATE_ACTIVE  STRING  COMMENT  '数据仓库记录生效日期',
END_DATE_ACTIVE    STRING  COMMENT  '数据仓库记录失效日期',
ENABLE_FLAG        STRING  COMMENT  '数据仓库记录是否最新记录 T最新，其他历史'
)COMMENT '项目-仓库对应关系表'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036'
STORED AS PARQUET;