DROP TABLE IF EXISTS DMK.DMK_FIN_INCOMECOST_M;
CREATE TABLE IF NOT EXISTS DMK.DMK_FIN_INCOMECOST_M(
PERIOD_WID                    BIGINT                             COMMENT  '期间ID',
YEAR                          BIGINT                             COMMENT  '年份ID',
MONTH                         BIGINT                             COMMENT  '月份ID',
OC_ID                         STRING                             COMMENT  '运营中心ID',
RGN_ID                        STRING                             COMMENT  '大区ID',
BASE_ID                       STRING                             COMMENT  '基地ID',
BRAND_ID                      STRING                             COMMENT  '品牌ID',
PROJ_ID                       STRING                             COMMENT  '项目ID',
VCL_MANAGER_INCOME_AMT        decimal(32,8)                      COMMENT  '整车管理费收入',
VCL_RENT_INCOME_AMT           decimal(32,8)                      COMMENT  '整车租金收入',
SECURE_CLEAN_INCOME_AMT       decimal(32,8)                      COMMENT  '整车保安保洁收入',
OTHER_VAT_INCOME_AMT          decimal(32,8)                      COMMENT  '整车其它增值税收入',
STORE_MANAGER_COST_AMT        decimal(32,8)                      COMMENT  '仓储管理成本',
RENT_COST_AMT                 decimal(32,8)                      COMMENT  '租金成本',
SECURE_CLEAN_COST_AMT         decimal(32,8)                      COMMENT  '保安保洁成本',
OTHER_VAT_COST_AMT            decimal(32,8)                      COMMENT  '其它增值服务成本',
TP_BIZ_INCOME_AMT             decimal(32,8)                      COMMENT  '运输业务收入',
STORE_BIZ_INCOME_AMT          decimal(32,8)                      COMMENT  '仓储业务收入',
SAL_INCOME_AMT                decimal(32,8)                      COMMENT  '销售收入',
BIZ_INCOME_PLAN_AMT           decimal(32,8)                      COMMENT  '营业收入计划',
TP_BIZ_COST_AMT               decimal(32,8)                      COMMENT  '运输业务成本',
STORE_BIZ_COST_AMT            decimal(32,8)                      COMMENT  '仓储业务成本',
SAL_COST_AMT                  decimal(32,8)                      COMMENT  '销售成本',
PROFIT_PLAN_AMT               decimal(32,8)                      COMMENT  '利润计划',
AR_RETURN_AMT                 decimal(32,8)                      COMMENT  '月应收账款回款金额',
AR_RETURN_TGT_AMT             decimal(32,8)                      COMMENT  '回款完成率月目标',
PERIOD_COST_AMT               decimal(32,8)                      COMMENT  '期间费用',
BIZ_INCOME_AMT                decimal(32,8)                      COMMENT  '营业收入',
OUT_BIZ_INCOME_AMT            decimal(32,8)                      COMMENT  '营业外收入',
BIZ_COST_AMT                  decimal(32,8)                      COMMENT  '营业成本',
OUT_BIZ_COST_AMT              decimal(32,8)                      COMMENT  '营业外支出',
VCL_INCOME_AMT                decimal(32,8)                      COMMENT  '整车收入',
VCL_COST_AMT                  decimal(32,8)                      COMMENT  '整车成本',
PROFIT_AMT                    decimal(32,8)                      COMMENT  '利润金额',
TP_PROFIT_AMT                 decimal(32,8)                      COMMENT  '运输业务利润',
STR_PROFIT_AMT                decimal(32,8)                      COMMENT  '仓储业务利润',
SAL_PROFIT_AMT                decimal(32,8)                      COMMENT  '销售业务利润',
MARKET_EXPAND_INCOME_AMT      decimal(32,8)                      COMMENT  '市场拓展收入金额',
MARKET_EXPAND_INCOME_TGT_AMT  decimal(32,8)                      COMMENT  '目标市场拓展收入金额',
HUMAN_COST_AMT                decimal(32,8)                      COMMENT  '人力成本',
SOURCE_CODE                   STRING                             COMMENT  '源系统标识',
INTEGRATION_ID                STRING                             COMMENT  '记录唯一标识',
AUX1_CHANGED_ON_DT            STRING                             COMMENT  '原系统记录创建时间',
W_INSERT_DT                   STRING                             COMMENT  '数据仓库插入时间',
W_UPDATE_DT                   STRING                             COMMENT  '数据仓库修改时间'
) 
COMMENT '整车中心收入成本月统计'
PARTITIONED BY(PART_SC STRING COMMENT  '数据来源',PART_DT STRING COMMENT  '分区时间')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036'
STORED AS PARQUET;