DROP TABLE IF EXISTS ODS_ZCOTM.STG_CM_XX_T_STOCK_TRANS_FACTORY_IN;
create table ODS_ZCOTM.STG_CM_XX_T_STOCK_TRANS_FACTORY_IN
(
  seqno                          decimal(32,8),
  transaction_id                 decimal(32,8),
  org_id                         decimal(32,8),
  organization_id                decimal(32,8),
  aim_organization_id            decimal(32,8),
  factory_organization_id        decimal(32,8),
  transaction_type_id            decimal(32,8),
  transaction_type_code          string,
  transaction_type_name          string,
  transaction_source             decimal(32,8),
  transaction_source_code        string,
  transaction_source_name        string,
  transaction_type_category_code string,
  transaction_type_category_name string,
  item_id                        decimal(32,8),
  item_code                      string,
  lot_number                     string,
  transaction_date               string,
  production_date                string,
  transaction_quantity           decimal(32,8),
  vin_code                       string,
  driver_id                      decimal(32,8),
  driver_code                    string,
  driver_name                    string,
  driver_line_id                 decimal(32,8),
  driver_line_code               string,
  driver_line_name               string,
  order_number                   string,
  source_number                  string,
  source_storage_location_id     decimal(32,8),
  source_storage_location_code   string,
  source_storage_location_name   string,
  source_storage_area_id         decimal(32,8),
  source_storage_area_code       string,
  source_storage_area_name       string,
  source_storage_room_id         decimal(32,8),
  source_storage_room_code       string,
  source_storage_room_name       string,
  aim_storage_location_id        decimal(32,8),
  aim_storage_location_code      string,
  aim_storage_location_name      string,
  aim_storage_area_id            decimal(32,8),
  aim_storage_area_code          string,
  aim_storage_area_name          string,
  aim_storage_room_id            decimal(32,8),
  aim_storage_room_code          string,
  aim_storage_room_name          string,
  position_info_id               decimal(32,8),
  position_info_code             string,
  position_info_name             string,
  remarks                        string,
  code_combinations              string,
  status_info_id                 decimal(32,8),
  status_code                    string,
  status_name                    string,
  status_seq                     decimal(32,8),
  status_description             string,
  erp_transaction_date           string,
  order_detail_id                string,
  created_by                     decimal(32,8),
  creation_date                  string,
  last_updated_by                decimal(32,8),
  last_update_date               string,
  last_update_login              string,
  operation_type                 string,
  process_flag                   string,
  attribute1                     string,
  attribute2                     string,
  attribute3                     string,
  attribute4                     string,
  attribute5                     string,
  attribute6                     string,
  attribute7                     string,
  attribute8                     string,
  attribute9                     string,
  attribute10                    string,
  domain_name                    string,
  insert_user                    string,
  insert_date                    string,
  update_user                    string,
  update_date                    string
)
COMMENT 'all etl'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\036'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;



DROP TABLE IF EXISTS ODS_ZCOTM.CM_XX_T_STOCK_TRANS_FACTORY_IN;
create table ODS_ZCOTM.CM_XX_T_STOCK_TRANS_FACTORY_IN
(
  seqno                          decimal(32,8),
  transaction_id                 decimal(32,8),
  org_id                         decimal(32,8),
  organization_id                decimal(32,8),
  aim_organization_id            decimal(32,8),
  factory_organization_id        decimal(32,8),
  transaction_type_id            decimal(32,8),
  transaction_type_code          string,
  transaction_type_name          string,
  transaction_source             decimal(32,8),
  transaction_source_code        string,
  transaction_source_name        string,
  transaction_type_category_code string,
  transaction_type_category_name string,
  item_id                        decimal(32,8),
  item_code                      string,
  lot_number                     string,
  transaction_date               string,
  production_date                string,
  transaction_quantity           decimal(32,8),
  vin_code                       string,
  driver_id                      decimal(32,8),
  driver_code                    string,
  driver_name                    string,
  driver_line_id                 decimal(32,8),
  driver_line_code               string,
  driver_line_name               string,
  order_number                   string,
  source_number                  string,
  source_storage_location_id     decimal(32,8),
  source_storage_location_code   string,
  source_storage_location_name   string,
  source_storage_area_id         decimal(32,8),
  source_storage_area_code       string,
  source_storage_area_name       string,
  source_storage_room_id         decimal(32,8),
  source_storage_room_code       string,
  source_storage_room_name       string,
  aim_storage_location_id        decimal(32,8),
  aim_storage_location_code      string,
  aim_storage_location_name      string,
  aim_storage_area_id            decimal(32,8),
  aim_storage_area_code          string,
  aim_storage_area_name          string,
  aim_storage_room_id            decimal(32,8),
  aim_storage_room_code          string,
  aim_storage_room_name          string,
  position_info_id               decimal(32,8),
  position_info_code             string,
  position_info_name             string,
  remarks                        string,
  code_combinations              string,
  status_info_id                 decimal(32,8),
  status_code                    string,
  status_name                    string,
  status_seq                     decimal(32,8),
  status_description             string,
  erp_transaction_date           string,
  order_detail_id                string,
  created_by                     decimal(32,8),
  creation_date                  string,
  last_updated_by                decimal(32,8),
  last_update_date               string,
  last_update_login              string,
  operation_type                 string,
  process_flag                   string,
  attribute1                     string,
  attribute2                     string,
  attribute3                     string,
  attribute4                     string,
  attribute5                     string,
  attribute6                     string,
  attribute7                     string,
  attribute8                     string,
  attribute9                     string,
  attribute10                    string,
  domain_name                    string,
  insert_user                    string,
  insert_date                    string,
  update_user                    string,
  update_date                    string
)
COMMENT 'all etl'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\036'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;



DROP TABLE IF EXISTS ODS_ZCOTM.HIS_CM_XX_T_STOCK_TRANS_FACTORY_IN;
create table ODS_ZCOTM.HIS_CM_XX_T_STOCK_TRANS_FACTORY_IN
(
  seqno                          decimal(32,8),
  transaction_id                 decimal(32,8),
  org_id                         decimal(32,8),
  organization_id                decimal(32,8),
  aim_organization_id            decimal(32,8),
  factory_organization_id        decimal(32,8),
  transaction_type_id            decimal(32,8),
  transaction_type_code          string,
  transaction_type_name          string,
  transaction_source             decimal(32,8),
  transaction_source_code        string,
  transaction_source_name        string,
  transaction_type_category_code string,
  transaction_type_category_name string,
  item_id                        decimal(32,8),
  item_code                      string,
  lot_number                     string,
  transaction_date               string,
  production_date                string,
  transaction_quantity           decimal(32,8),
  vin_code                       string,
  driver_id                      decimal(32,8),
  driver_code                    string,
  driver_name                    string,
  driver_line_id                 decimal(32,8),
  driver_line_code               string,
  driver_line_name               string,
  order_number                   string,
  source_number                  string,
  source_storage_location_id     decimal(32,8),
  source_storage_location_code   string,
  source_storage_location_name   string,
  source_storage_area_id         decimal(32,8),
  source_storage_area_code       string,
  source_storage_area_name       string,
  source_storage_room_id         decimal(32,8),
  source_storage_room_code       string,
  source_storage_room_name       string,
  aim_storage_location_id        decimal(32,8),
  aim_storage_location_code      string,
  aim_storage_location_name      string,
  aim_storage_area_id            decimal(32,8),
  aim_storage_area_code          string,
  aim_storage_area_name          string,
  aim_storage_room_id            decimal(32,8),
  aim_storage_room_code          string,
  aim_storage_room_name          string,
  position_info_id               decimal(32,8),
  position_info_code             string,
  position_info_name             string,
  remarks                        string,
  code_combinations              string,
  status_info_id                 decimal(32,8),
  status_code                    string,
  status_name                    string,
  status_seq                     decimal(32,8),
  status_description             string,
  erp_transaction_date           string,
  order_detail_id                string,
  created_by                     decimal(32,8),
  creation_date                  string,
  last_updated_by                decimal(32,8),
  last_update_date               string,
  last_update_login              string,
  operation_type                 string,
  process_flag                   string,
  attribute1                     string,
  attribute2                     string,
  attribute3                     string,
  attribute4                     string,
  attribute5                     string,
  attribute6                     string,
  attribute7                     string,
  attribute8                     string,
  attribute9                     string,
  attribute10                    string,
  domain_name                    string,
  insert_user                    string,
  insert_date                    string,
  update_user                    string,
  update_date                    string
)
COMMENT 'all etl'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\036'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;








