DROP TABLE IF EXISTS DMR.DMR_YD_OV_DTD_OVR_ORD_DTL;
CREATE TABLE IF NOT EXISTS DMR.DMR_YD_OV_DTD_OVR_ORD_DTL(
MONTH_ID    STRING    COMMENT    '月份ID'
,RNG_ID    STRING    COMMENT    '大区ID'
,RNG_NAME    STRING    COMMENT    '大区名称'
,BASE_ID    STRING    COMMENT    '基地ID'
,BASE_NAME    STRING    COMMENT    '基地名称'
,BRAND_ID    STRING    COMMENT    '品牌ID'
,BRAND_NAME    STRING    COMMENT    '品牌名称'
,TP_MODE_ID    STRING    COMMENT    '运输方式ID'
,TP_MODE_NAME    STRING    COMMENT    '运输方式名称'
,ORDER_RELEASE_NAME     STRING    COMMENT    '订单号'
,WHOLE_OVER_TIME    DECIMAL(32,8)    COMMENT    '整体超时时长'
,CATD_ONE_OVER_TIME    DECIMAL(32,8)    COMMENT    '超时时长(接单-分配)'
,CATD_TWO_OVER_TIME    DECIMAL(32,8)    COMMENT    '超时时长(分配-出库)'
,CATD_THREE_OVER_TIME    DECIMAL(32,8)    COMMENT    '超时时长(接车-打单)'
,CATD_FOUR_OVER_TIME    DECIMAL(32,8)    COMMENT    '超时时长(发运-交付)'
,INSERT_TIME    STRING    COMMENT    '插入时间'
,UPDATE_TIME    STRING    COMMENT    '更新时间'
) COMMENT '整车物流总览月度DTD时长详情（超时订单明细）'
PARTITIONED BY(PART_SC STRING COMMENT  '数据来源',PART_DT STRING COMMENT  '分区时间')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036'
STORED AS PARQUET;