DROP TABLE IF EXISTS DMR.DMR_YD_MKT_SHARE_DTL;
CREATE TABLE IF NOT EXISTS DMR.DMR_YD_MKT_SHARE_DTL(
MONTH_ID    STRING    COMMENT    '月份ID'
,RNG_ID    STRING    COMMENT    '大区ID'
,RNG_NAME    STRING    COMMENT    '大区名称'
,BASE_ID    STRING    COMMENT    '基地ID'
,BASE_NAME    STRING    COMMENT    '基地名称'
,BRAND_ID    STRING    COMMENT    '品牌ID'
,BRAND_NAME    STRING    COMMENT    '品牌名称'
,PROD_ID    STRING    COMMENT    '产品ID'
,PROD_NAME    STRING    COMMENT    '产品名称'
,MKT_EXP_INCOME		DECIMAL(32,8)	COMMENT		'市场拓展收入'
,CUR_M_MKT_SHARE    DECIMAL(32,8)    COMMENT    '当月市场占有率'
,LST_M_MKT_SHARE    DECIMAL(32,8)    COMMENT    '上月市场占有率'
,MKT_SHARE_M_MOM    DECIMAL(32,8)    COMMENT    '环比增减'
,MOM_WRN_FLAG    BIGINT    COMMENT    '环比预警标志'
,INSERT_TIME    STRING    COMMENT    '插入时间'
,UPDATE_TIME    STRING    COMMENT    '更新时间'
) COMMENT '整车物流市场占有率'
PARTITIONED BY(PART_SC STRING COMMENT  '数据来源',PART_DT STRING COMMENT  '分区时间')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036'
STORED AS PARQUET;