DROP TABLE IF EXISTS DMR.DMR_YD_TP_BIS_QAT_LOS_D;
CREATE TABLE IF NOT EXISTS DMR.DMR_YD_TP_BIS_QAT_LOS_D(
DATE_ID    STRING    COMMENT    '时间ID'
,LST_DAY_FLAG    STRING    COMMENT    '月末标志'
,RNG_ID    STRING    COMMENT    '大区ID'
,RNG_NAME    STRING    COMMENT    '大区名称'
,BASE_ID    STRING    COMMENT    '基地ID'
,BASE_NAME    STRING    COMMENT    '基地名称'
,BRAND_ID    STRING    COMMENT    '品牌ID'
,BRAND_NAME    STRING    COMMENT    '品牌名称'
,CUR_M_QAT_LOS_RATE    DECIMAL(32,8)    COMMENT    '当前月在途质损率'
,CUR_Y_QAT_LOS_RATE    DECIMAL(32,8)    COMMENT    '当前年在途质损率'
,WRN_M_FLAG    BIGINT    COMMENT    '月度在途质损率预警标志'
,WRN_Y_FLAG    BIGINT    COMMENT    '年度在途质损率预警标志'
,INSERT_TIME    STRING    COMMENT    '插入时间'
,UPDATE_TIME    STRING    COMMENT    '更新时间'
) COMMENT '整车物流运输在途质损率'
PARTITIONED BY(PART_SC STRING COMMENT  '数据来源',PART_DT STRING COMMENT  '分区时间')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036'
STORED AS PARQUET;