DROP TABLE IF EXISTS DMR.DMR_YD_TP_BIS_SHIP_ONTIME_D;
CREATE TABLE IF NOT EXISTS DMR.DMR_YD_TP_BIS_SHIP_ONTIME_D(
DATE_ID    STRING    COMMENT    '时间ID'
,LST_DAY_FLAG    STRING    COMMENT    '月末标志'
,RNG_ID    STRING    COMMENT    '大区ID'
,RNG_NAME    STRING    COMMENT    '大区名称'
,BASE_ID    STRING    COMMENT    '基地ID'
,BASE_NAME    STRING    COMMENT    '基地名称'
,BRAND_ID    STRING    COMMENT    '品牌ID'
,BRAND_NAME    STRING    COMMENT    '品牌名称'
,CUR_M_SHIP_ONTIME_RATE    DECIMAL(32,8)    COMMENT    '当前月发运准时率'
,CUR_Y_SHIP_ONTIME_RATE    DECIMAL(32,8)    COMMENT    '当前年发运准时率'
,WRN_M_FLAG    BIGINT    COMMENT    '月度预警标志'
,WRN_Y_FLAG    BIGINT    COMMENT    '年度预警标志'
,INSERT_TIME    STRING    COMMENT    '插入时间'
,UPDATE_TIME    STRING    COMMENT    '更新时间'
) COMMENT '整车物流运输发运准时率'
PARTITIONED BY(PART_SC STRING COMMENT  '数据来源',PART_DT STRING COMMENT  '分区时间')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\036'
STORED AS PARQUET;
